# Based on https://raw.githubusercontent.com/bluesky-social/pds/main/compose.yaml
version: '3.9'
services:
  caddy:
    container_name: caddy
    image: caddy:2
    network_mode: host
    depends_on:
      - pds
    restart: unless-stopped
    volumes:
      - type: bind
        source: /pds/caddy/data
        target: /data
      - type: bind
        source: /pds/caddy/etc/caddy
        target: /etc/caddy
  pds:
    container_name: pds
#    image: ghcr.io/bluesky-social/pds:0.4
#    original image redirect: https://github.com/bluesky-social/pds/pkgs/container/pds/312660075?tag=sha-9ac9461ce2e4ed7ac66889bb1017662a2f846c98
#    gemmy image deployment: docker pull ghcr.io/gemmysocial/atproto:sha-c6ed1ee
    image: ghcr.io/gemmysocial/atproto:sha-c6ed1ee
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: /pds
        target: /pds
    env_file:
      - /pds/pds.env
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    network_mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: "@midnight"